# Generated by Django 6.0.3 on 2026-03-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to='members/'),
        ),
    ]
