# Generated by Django 6.0.3 on 2026-03-17 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_date_of_birth_remove_member_email_and_more'),
        ('plans', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='membership_start_date',
            new_name='join_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_end_date',
        ),
        migrations.AddField(
            model_name='member',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan'),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.trainer'),
        ),
    ]
