# Generated by Django 6.0.3 on 2026-03-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_membership_start_date_member_join_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
